name: 'Terraform init'
runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18.0'
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.8
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform init
      run: terraform init