name: Terraform Deploy
env:
  PASSWD: ${{ secrets.GRAFANA_PASSWORD }}
on:
  push:
    branches:
      - dev

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    uses: actions/awesome-eyes@v1
    if: github.event_name == 'pull_request'
    steps:
      - name: Terraform format
        run: terraform fmt -check
      - name: Terraform validate
        run: terraform validate -no-color
      - name: Terraform plan
        run: terraform plan -no-color -var "grafana_admin_password=env.PASSWD"
        continue-on-error: true

  terraform-deploy:
    runs-on: ubuntu-latest
    uses: actions/awesome-eyes@v1
    steps:
      - name: Terraform deploy
        run: terraform apply -var "grafana_admin_password=env.PASSWD" --auto-approve
      # - name: Terraform test
      #   run: cd test && go test -v
      - name: Terraform destroy
        run: terraform destroy --auto-approve
